t ?= esp32
p ?= cpm22

TERMINAL_SPEED := 115200
TERMINAL_EXTRA_FLAGS := -C serialout.txt
#CPPFLAGS = -DDEBUGGING=0xff -DCPU_DEBUG=false -DUNDOCUMENTED_OPS
CPPFLAGS = -DUNDOCUMENTED_OPS
LIBRARIES = SimpleTimer
FS_DIR := disks/$p
SD_DIR := \"/$p/\"

ifeq ($t, rp2040)
BOARD := adafruit_feather_dvi
flash := 8388608_2097152
CPPFLAGS += -DUSE_HOST_KBD -DDVI_BIT_DEPTH=1 -DDVI_RESOLUTION=DVI_RES_640x240p60
LIBRARIES += LittleFS PicoDVI Adafruit_GFX Adafruit_BusIO Wire
endif

ifeq ($t, esp8266)
BOARD := d1_mini
baud := 921600
eesz := 4M1M
CPPFLAGS += -DUSER_SETUP_LOADED -DILI9341_DRIVER -DTFT_CS=PIN_D8 -DTFT_DC=PIN_D1 \
	-DTFT_RST=-1 -DSPI_FREQUENCY=40000000 -DLOAD_GLCD -DLOAD_GFXFF \
	-DHARDWARE_H=\"hw/esp8bit.h\" -DPS2_SERIAL_KBD=\"UK\"
LIBRARIES += PS2KeyAdvanced PS2KeyMap TFT_eSPI SpiRAM FS LittleFS
endif

ifeq ($t, esp32)
TERMINAL_SPEED = 115200
CPPFLAGS += -DUSE_UZ80
LIBRARIES += FS

ifeq ($b, lilygo)
BOARD := ttgo-t7-v14-mini32
SERIAL_PORT := /dev/ttyACM0
CPPFLAGS += -DPS2_SERIAL_KBD=\"UK\" -DUSE_SD -DPROGRAMS=$(SD_DIR) -DVGA_BIT_DEPTH=1 -DVGA_RESOLUTION=VGAMode::MODE640x480
LIBRARIES += PS2KeyAdvanced PS2KeyMap ESP32Lib SD

else ifeq ($b, olimex)
BOARD := esp32-sbc-fabgl
TERMINAL_EXTRA_FLAGS := -C serialout.txt
SERIAL_PORT := /dev/ttyUSB0
DebugLevel := verbose
CPPFLAGS += -DUSE_HOST_KBD -DUSE_SD -DVGA_BIT_DEPTH=1 -DVGA_RESOLUTION=VGAMode::MODE640x480 -DVGA_FONT=Font8x8
LIBRARIES += ESP32Lib SD

else ifeq ($b, wrover)
BOARD := esp32wrover
CPPFLAGS += -DHARDWARE_H=\"hw/esp32-example.h\" -DUSE_HOST_KBD -DUSE_HOST_DISPLAY -DUSE_SD -DSD_CS=5 -DPROGRAMS=$(SD_DIR)
LIBRARIES += SD
else
BOARD := lolin32
CPPFLAGS += -DUSER_SETUP_LOADED -DILI9341_DRIVER -DTFT_CS=5 -DTFT_DC=2 -DTFT_RST=-1 -DSPI_FREQUENCY=40000000 -DLOAD_GLCD \
	-DHARDWARE_H=\"hw/esp32-example.h\" -DUSE_HOST_KBD
LIBRARIES += TFT_eSPI SPIFFS
endif
endif

include $t.mk
